### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xfe in position 0: illegal multibyte sequence

### ISSUE THREAD

**Issue by SummerSec** [yhy0/SScan#1]
![image](https://user-images.githubusercontent.com/47944478/104420077-4d0b6a00-55b4-11eb-9dab-5bcd6307e10d.png)

**Comment by yhy0** [comment]
huawei.txt 文件里应该有没法识别的字符， 您可以把 SScan.py 的 180 行 改成
with open(input_file, encoding='UTF-8') as inFile:

![image](https://user-images.githubusercontent.com/31311038/104420833-71b41180-55b5-11eb-99df-7066678e7ecd.png)
这样试一下， 或者您看下您的huawei.txt 文件中是不是有特殊字符。

**Comment by SummerSec** [comment]
![image](https://user-images.githubusercontent.com/47944478/104421429-4978e280-55b6-11eb-9997-551ae02a46c9.png)

**Comment by yhy0** [comment]
没考虑到 windows 下的路径写法，您只需要把 lib/common/scanner.py 下的 490 行 改成这样就可以了
` if _script.startswith('scripts/__') or _script.startswith('scripts\\__'):`

![image](https://user-images.githubusercontent.com/31311038/104425878-26e9c800-55bc-11eb-9dc5-ed2e9a5ad93c.png)

SScan.py 的 122行左右 最好也改一下编码
`with open(_script, encoding='UTF-8') as f:`
![image](https://user-images.githubusercontent.com/31311038/104426026-58fb2a00-55bc-11eb-9a5c-3a21b5c989e9.png)


而且我在windows下试了一下，ctrl c 退出还有问题，目标多了检测时间还会很长，403 绕过也会有很多误报，最近没时间修改，请担待。
感谢您的反馈

**Comment by SummerSec** [comment]
ok
